### ISSUE TITLE
How is this library better than cinnamon for play framework

### ISSUE THREAD

**Issue by kolapkardhaval** [stijndehaes/play-prometheus-filters#19]
I am going through cinnamon which support prometheus as well:

https://www.lightbend.com/blog/lightbend-cinnamon-play-framework

I like your project and debating which one to go for. Do you know of advantages over cinnamon?

**Comment by stijndehaes** [comment]
I thought you needed a license to use cinnamon in production. Or at least when I started making this you needed a license. That was a license for the whole lightbend stack and we weren't planning on using the rest so it was too expensive. Also at that point I believe there was no prometheus integration and our monitoring stack was prometheus based.

So maybe the reasons aren't valid anymore. Anyway if you could let me know what your findings are it would be very much appreciated.

**Comment by co-category** [comment]
@stijndehaes you are correct. From investigations you do need a license for this. Lightbend will then issue a username and password which will give access to the Bintray to include the dependency in a project. Even though it looks ok, I will not pay Lightbend for this because, as you have demonstrated, it's not difficult to get this integration done oneself.
